### grpc/ping/values.ymal
replicaCount: 1

image:
  repository: shinwoohipo/grpc-ping-service
  tag: "1.0.0"
  pullPolicy: Always

service:
  name: grpc
  type: ClusterIP
  port: 50151
  targetPort: 50151  # containerPort 로 mapping됨
  containerPort: 50151

command:
  - python
  - server.py

nfs:
  server: nas.host.sh
  path: /volume1/django/192.168.10.249/media
  size: 200Gi


### 별도 env.yaml 로 관리함 : update시, 붙여 넣기
### deployment.yaml 에서 env 추가함.
env:
  - name: IS_DOCKER
    value: "true"
  - name: GRPC_PORT
    value: "50151"
  - name: MAX_WORKERS
    value: "3"



# volumeMounts:
#   - name: grpc-ping-media
#     mountPath: /app/media


# volumes:
#   - name: grpc-ping-media
#     persistentVolumeClaim:
#       claimName: grpc-ping-media-pvc


resources: {}

# nodeSelector:
#   dns-role: "true"

tolerations: []
### deployment.yaml 에서 Affinity 추가함.
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: grpc.cluster
            operator: In
            values: ["role"]
          - key: env
            operator: In
            values: ["production"]


### ✅ serviceaccount.yaml 용
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

### ✅ ingress-health.yaml 용
### ingress.yaml 에서도  true면 맨 앞단에 추가함.
ingressHealth:
  namePostfix: ingress-health
  enabled: false

### ✅ ingress.yaml 용
ingress:
  enabled: false
  # className: traefik
  # annotations:
  #   traefik.ingress.kubernetes.io/router.entrypoints: grpc
  #   traefik.ingress.kubernetes.io/protocol: h2c
  # hosts:
  #   - host: ping.grpc.sh
  #     paths:
  #       - path: /
  #         pathType: Prefix
  #         backend:
  #           service:
  #             name: ping
  #             port:
  #               number: 5555
  # tls: []

### ✅ ingress-route.yaml 용
ingressRoute:
  enabled: true
  routes:
    - Host: "ping.grpc.sh"
      Port: 50151

### ✅ httproute.yaml 용 ==> 단순한거라, 그냥 ingress 사용함.
httpRoute:
  enabled: false

### ✅ hpa.yaml 용
autoscaling:
  enabled: false

