# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ping.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ping.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nping.proto\x12\x04ping\"\x1e\n\x0bPingRequest\x12\x0f\n\x07ip_list\x18\x01 \x03(\t\"/\n\nPingResult\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x11\n\treachable\x18\x02 \x01(\x08\"1\n\x0cPingResponse\x12!\n\x07results\x18\x01 \x03(\x0b\x32\x10.ping.PingResult2@\n\x0bPingService\x12\x31\n\x08\x43heckIPs\x12\x11.ping.PingRequest\x1a\x12.ping.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ping_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=20
  _globals['_PINGREQUEST']._serialized_end=50
  _globals['_PINGRESULT']._serialized_start=52
  _globals['_PINGRESULT']._serialized_end=99
  _globals['_PINGRESPONSE']._serialized_start=101
  _globals['_PINGRESPONSE']._serialized_end=150
  _globals['_PINGSERVICE']._serialized_start=152
  _globals['_PINGSERVICE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
